name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.4

      - name: Set up Python (if needed)
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generate_packages.sh
        run: |
          chmod +x ./generate_packages.sh
          ./generate_packages.sh
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT }}

      - name: Commit updated metadata (if any)
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add public/Packages* public/Release || echo "Nothing to add"
          git commit -m "Update Packages metadata" || echo "No changes to commit"
          git push https://${{ secrets.PAT }}@github.com/axs66/repo.git HEAD:main

      - name: Check for metadata changes
        id: check_changes
        run: |
          if git diff --quiet HEAD; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT

      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload artifact
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './public'

      - name: Deploy to GitHub Pages
        if: steps.check_changes.outputs.no_changes == 'false'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
