name: Deploy Repo with Sileo Support

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate metadata
        run: |
          chmod +x ./generate_packages.sh
          ./generate_packages.sh
          [ -f Packages ] || { echo "::error::Packages 生成失败"; exit 1; }

      - name: Prepare artifact
        run: |
          mkdir -p gh-pages
          # 复制核心文件
          cp {index.html,Release,CydiaIcon.png,sileo-featured.json} gh-pages/ 2>/dev/null || true
          cp Packages* gh-pages/
          # 复制资源目录
          cp -r {js,icon,images,sileodepiction} gh-pages/ 2>/dev/null || true
          # 验证图标存在
          [ -f gh-pages/CydiaIcon.png ] || echo "::error::必须提供 CydiaIcon.png"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'gh-pages'

      - name: Deploy
        uses: actions/deploy-pages@v4
